<%
const TT_DEFAULT_PLACEHOLDER_BEGIN = "<<< "
const TT_DEFAULT_PLACEHOLDER_END = " >>>"
const TT_BLOCKBEGIN	= "BLOCK"
const TT_BLOCKEND = "ENDBLOCK"
const TT_VALIDVARNAMES = "[(a-zA-Z0-9)|_]+"
%>